<?php

// Generated by generate_ast.php on 03/Sep/2023

namespace Lox;

class Binary extends Expr
{
    public Expr $left;
    public Token $operator;
    public Expr $right;
    public function __construct(Expr $left, Token $operator, Expr $right)
    {
        $this->left = $left;
        $this->operator = $operator;
        $this->right = $right;
    }

    public function accept(ExprVisitor $visitor): mixed
    {
        return $visitor->visitBinaryExpr($this);
    }
}
