<?php

// Generated by generate_ast.php on 03/Sep/2023

namespace Lox;

interface ExprVisitor
{
    public function visitBinaryExpr(Binary $expr): mixed;
    public function visitGroupingExpr(Grouping $expr): mixed;
    public function visitLiteralAstExpr(LiteralAst $expr): mixed;
    public function visitUnaryExpr(Unary $expr): mixed;
}
