<?php

// Generated by generate_ast.php on 03/Sep/2023

namespace Lox;
trait ExprVisitor {
    abstract function visitBinaryExpr(Binary $expr) : mixed;
    abstract function visitGroupingExpr(Grouping $expr) : mixed;
    abstract function visitLiteralAstExpr(LiteralAst $expr) : mixed;
    abstract function visitUnaryExpr(Unary $expr) : mixed;
}