<?php

// Generated by generate_ast.php on 03/Sep/2023

namespace Lox;
interface ExprVisitor {
    function visitBinaryExpr(Binary $expr) : mixed;
    function visitGroupingExpr(Grouping $expr) : mixed;
    function visitLiteralAstExpr(LiteralAst $expr) : mixed;
    function visitUnaryExpr(Unary $expr) : mixed;
}