<?php

// Generated by generate_ast.php on 03/Sep/2023

namespace Lox;

class LiteralAst extends Expr
{
    public Literal $value;
    public function __construct(Literal $value)
    {
        $this->value = $value;
    }

    public function accept(ExprVisitor $visitor): mixed
    {
        return $visitor->visitLiteralAstExpr($this);
    }
}
